### ISSUE TITLE
Spectators can move GUI items when trade is cancelled.

### ISSUE THREAD

**Issue by danjono** [Trophonix/TradePlus#1]
If you are spectating a trade, once the players have finished the trade or canceled, anyone who is spectating can freely move the items in the GUI or move them into their own inventory.

[Screenshot](https://i.imgur.com/9qyHoll.png)

Running Spigot 1.12.2

**Comment by Trophonix** [comment]
Sorry for the late reply, but I will work on this issue tonight. Thanks
