### ISSUE TITLE
Players lose items after denying trades

### ISSUE THREAD

**Issue by AmazedMender16** [Trophonix/TradePlus#12]
Server version 1.12.2

https://pastebin.com/YbzJwCji

**Comment by AmazedMender16** [comment]
People are losing all their xp after a trade of exp please look into this @Trophonix

**Comment by DeadMaster121** [comment]
Probably something to do with your config? Send it here on a pastebin.

``java.lang.IllegalArgumentException: Experience progress must be between 0.0 and 1.0 (NaN)``

**Comment by AmazedMender16** [comment]
Where there many config changes since a few versions?

**Comment by AmazedMender16** [comment]
Its still happening even with new config files

**Comment by Trophonix** [comment]
Sorry, I haven't been able to get on Github or Spigot recently. I am going to look into this issue now.

**Comment by Trophonix** [comment]
In case you didn't see: https://github.com/Trophonix/TradePlus/releases/tag/2.54
