### ISSUE TITLE
Players losing their items

### ISSUE THREAD

**Issue by AmazedMender16** [Trophonix/TradePlus#13]
I traded 1 bottle of 100K xp with DonTuMaD for 8 vote keys, but when we did we both lost the stuff and neither of us received anything. I also saw that when a trade got canceled I "lost" the stuff but it got back in my inventory when I got another piece of the same item.

No error codes or anything in console.
V2.54

**Comment by Trophonix** [comment]
Ohh okay, so you did get the items back but an inventory glitch made them
invisible. Relogging would've also fixed it. Are you sure neither of you
closed the inventory before it ended the countdown? I will look into why it
would be treating an accepted trade as cancelled

**Comment by AmazedMender16** [comment]
Any update on this?

**Comment by AmazedMender16** [comment]
People keep losing their XP bottles

**Comment by Trophonix** [comment]
I can't imagine why you're having this problem. What server version are you
running exactly? What build tools revision if you know it

**Comment by Trophonix** [comment]
Can you send me a list of the plugins you have installed?

**Comment by AmazedMender16** [comment]
I have send it over PM on spigot

**Comment by AmazedMender16** [comment]
Any update on this??

**Comment by Trophonix** [comment]
I can't replicate this issue. I'm not sure what I can do.

**Comment by Cranite** [comment]
![TradePlus bug](https://i.imgur.com/8sp9j4Z.gif "TradePlus Bug")

I've found a bug that causes players to lose their items. If you hit a number that corresponds to an item in your hot bar, you can move that item to your cursor position, and back. As you can see in the image, moving the item works but moving the item back fails. Cancelling the trade permanently removes the item from existence, as does accepting the trade.

**Comment by Trophonix** [comment]
Hmm, I'll look into it. Thanks!

**Comment by Trophonix** [comment]
I found a couple issues that may have been causing item loss and fixed in the last couple versions. If anyone starts experiencing item loss again it will be considered a new issue.
