### ISSUE TITLE
1.13 Alpha Bug Reports

### ISSUE THREAD

**Issue by Trophonix** [Trophonix/TradePlus#15]
If you find any issues with the 1.13 alpha release of trade+, please report them here.

**Comment by M4rtyn4** [comment]
Error occurred while enabling TradePlus v2.54-1.13-ALPHA
[latest.log](https://github.com/Trophonix/TradePlus/files/2245107/latest.log)

**Comment by DjScripto** [comment]
I've had the same issue as M4rtyn4. When you start up the server with the plugin installed it gives off an error in console saying that it had a "floating decimal." Please fix this!

**Comment by Trophonix** [comment]
I'll look into this tonight, thank you!

**Comment by Trophonix** [comment]
@M4rtyn4 Should now be fixed, re-download the alpha.

@DjScripto That does not sound like the same issue that Martyn was experiencing. Please send me your logs.

**Comment by M4rtyn4** [comment]
[https://github.com/Trophonix/TradePlus/releases/tag/2.54-1.13-ALPHA](url) yes?
:(
[latest.log](https://github.com/Trophonix/TradePlus/files/2260711/latest.log)

**Comment by Trophonix** [comment]
Ahh, that was a dumb mistake on my part. Fixed it!

**Comment by M4rtyn4** [comment]
:(
[latest.log](https://github.com/Trophonix/TradePlus/files/2263044/latest.log)

**Comment by pvpKingdoms** [comment]
I am receiving the same error as M4rtyn4; says to change api to 1.13 config.

**Comment by Trophonix** [comment]
Ahh, that's something I missed when updating. Will upload fix

**Comment by Trophonix** [comment]
Alright, trade+ now runs on 1.13. I just want to reiterate to all of you that this is a beta version of a plugin running on an alpha version of a server software. Back up important data etc etc. I made a simple script to update people's configs to something that will work for 1.13 but it won't catch everything, so you may need to go through manually and fix your configs. 

For example,

`160:14`
becomes
`red_stained_glass_pane`

**Comment by pvpKingdoms** [comment]
https://pastebin.com/fiqta4QR

New error; not sure if I missed an item ID, or another config option. Went through a couple times and everything seems configured fine.

**Comment by pvpKingdoms** [comment]
> Alright, trade+ now runs on 1.13. I just want to reiterate to all of you that this is a beta version of a plugin running on an alpha version of a server software. Back up important data etc etc. I made a simple script to update people's configs to something that will work for 1.13 but it won't catch everything, so you may need to go through manually and fix your configs.

[Tue, 21. Aug 2018 01:32:11 EDT ERROR] Fatal error trying to convert TradePlus v2.54:com/trophonix/tradeplus/util/InvUtils.class
[Tue, 21. Aug 2018 01:32:11 EDT ERROR] Fatal error trying to convert TradePlus v2.54:com/trophonix/tradeplus/util/ItemFactory.class
[Tue, 21. Aug 2018 01:32:11 EDT ERROR] Error occurred while enabling TradePlus v2.54 (Is it up to date?)

**Comment by pvpKingdoms** [comment]
Everything works properly! Thank you so much for your work!
