### ISSUE TITLE
Cant accept trade

### ISSUE THREAD

**Issue by M4rtyn4** [Trophonix/TradePlus#19]
When people trade and they put stuff in and want to accept pressing accept wont do anything. 
Its 2.54 alpha
on Spigot 1.13.1

**Comment by Trophonix** [comment]
Any errors in console?

**Comment by M4rtyn4** [comment]
no :(

**Comment by Trophonix** [comment]
Ok im gonna test and see if I can find anything. Have you changed your
configs at all? Can you send me them?

**Comment by M4rtyn4** [comment]
Now on 1.13.2 and latest trade update it's all good
