### ISSUE TITLE
People can't move after trading

### ISSUE THREAD

**Issue by AmazedMender16** [Trophonix/TradePlus#24]
Spigot: 1.12.2 Latest
TradePlus: 3.12

Players are reporting that they can't move after trading ( works after relog )

**Comment by Trophonix** [comment]
Oh weird, I will check it out. No errors in console after a trade?

**Comment by AmazedMender16** [comment]
My bad... here it is: https://pastebin.com/Bgq2Ship

**Comment by Trophonix** [comment]
Hmm from that error it seems like your lang.yml is missing the "expired"
key and maybe others. Did you change your configs since you downloaded v3.1
or higher? I hope my configuration updating code isn't bugged, I tested it
and it seemed to work. I'll check again.

**Comment by AmazedMender16** [comment]
I have the LANG file from 3.11

**Comment by Trophonix** [comment]
Hmm yeah I didn't change that key in the update. You may need to add this
back to your Lang.yml

`expired: 'whatever you want to send when a request expires'`

**Comment by AmazedMender16** [comment]
Just did that... but dont think that will solve the not moving issue

**Comment by Trophonix** [comment]
Yeah the error you sent didn't include any info about the
InventoryCloseEvent error, just about the one in TradeCommand. Can you get
the whole error in a paste

**Comment by AmazedMender16** [comment]
Those were all the errors I saw..

**Comment by AmazedMender16** [comment]
Same here LOL! I'm getting these reports since upgrading from 2.55

**Comment by Trophonix** [comment]
I would guess your Lang is also missing the "canceled" item which would
cause it to crash in that area of the code but that's not certain.

**Comment by AmazedMender16** [comment]
Already added the missing ones ( looked at the old and new one )

**Comment by Trophonix** [comment]
Can you send your lang.yml so I can test with it in my server?

**Comment by AmazedMender16** [comment]
https://pastebin.com/NaXGu6HL

**Comment by Trophonix** [comment]
Odd, I can't get any kind of error to occur even with your lang file. Have you tested after you added the missing lang keys?

**Comment by AmazedMender16** [comment]
I didn’t see any errors after adding the missing lang entries... I believe I mentioned this earlier haha

**Comment by Trophonix** [comment]
Ah ok, but you're still having the movement issue?

**Comment by AmazedMender16** [comment]
Will let you know ASAP

**Comment by AmazedMender16** [comment]
Players are saying that it's not happening anymore
I will keep monitoring

**Comment by Trophonix** [comment]
In an update this week I will include some changes to how I send those messages so that stuff like this wouldn't cause the plugin to stop functioning.

**Comment by Trophonix** [comment]
Just released a change which will use the default messages instead of crashing in cases like this.
https://github.com/Trophonix/TradePlus/releases/tag/3.13
