### ISSUE TITLE
Spectate message not working

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#25]
The spectate message for staff with the perm tradeplus.admin does not fire a message that a trade was started. There is simply no message at all.
Tried with OP too, so it can't be a changed perm.
Tried a default config too on a default test server.

Using the latest version of Tradeplus 3.12

**Comment by Trophonix** [comment]
Hmm.. I think I know why it's not working. I'll get a fix out in an hour.

**Comment by Trophonix** [comment]
Fixed in https://github.com/Trophonix/TradePlus/commit/c9081a58c51280689aaaef22c269ad7f13959b21
Will be released soon.

**Comment by Trophonix** [comment]
https://github.com/Trophonix/TradePlus/releases/tag/3.13
