### ISSUE TITLE
Shift+RIGHT Click is not handled by plugin

### ISSUE THREAD

**Issue by jovanmanic** [Trophonix/TradePlus#31]
When player tries to fast send item (Shift+Right click) from inventory to trade, 5th item and on (6th, 7th...), get disappear. because 5th field in trade is barier between own trade items and other player items!

Video: https://www.youtube.com/watch?v=JkWguhzw4-E

**Comment by Trophonix** [comment]
Ahh that should be an easy fix, I'll check into it. Thanks

**Comment by jovanmanic** [comment]
Good, we wait for fix! :)

**Comment by Trophonix** [comment]
Working on compiling and uploading the update to fix this now.

**Comment by Trophonix** [comment]
Fixed in v3.20.
