### ISSUE TITLE
Issues trading claimblocks

### ISSUE THREAD

**Issue by techxnerd** [Trophonix/TradePlus#32]
Hi I'm a helper on one of the many Minecraft servers. We are running 1.13.2 paper and are having issues with players (without op) being able to trade over a certain # of claimblocks in the trade window. Any way of fixing this? Thank you!

**Comment by Trophonix** [comment]
I'm not sure I understand. Is it letting them trade more claim blocks than
they have? Or is it letting them trade more than a maximum?
