### ISSUE TITLE
Players losing their items 

### ISSUE THREAD

**Issue by djacks6278** [Trophonix/TradePlus#36]
if players try trade items in trade menu icon(ex: money-diamond, exp-exp bottle)
they losing item some time
but idk why they are
some reason from player
1.only have issue in trade icon item.
2.and if that icon item amount is 2 then player lose item
3.and if players click same position each others screen then item is can't see other player
3-1. that moment if player try trade complete item lose
4.or admin trying view some players trade lose item

5.this issue is not trust but some have
5-1.If the Player tries to place an item, such as an icon, in the same vertical line, they lose item.

ps. all happen if player close trade or complete trade

my server player report that issue and reason
1~4 is most reason
and 5 less reason

is just my think have fix
if player close trade - > check trade inv - > if trade inv still have item - > and all players don't have item - > item return to original player

or if click other players trade item and same item in icon re check item amount 

but i'm not major idk how do that this code
Once, I set as the icon bedrock. Actually no more problems, but I need an icon.

this is major issue i think cuz i have 15+ same issue report ..
my server is 1.12.2 and use protocolsupport
and no error logs
nothing.. idk why
if u can plz fix it

srry my bad eng

**Comment by Trophonix** [comment]
Thank you for reporting this bug. I have been hearing other reports of item loss with no errors. Will be doing extensive testing tomorrow to get it fixed.

**Comment by Trophonix** [comment]
Please see the latest release. I haven't been able to reproduce the item loss issues on my servers. I'm still doing testing but if I'm not able to see the bug happening and at what stage in the trade it's happening (to the precise line of code), I don't know how to fix the problem.

**Comment by Trophonix** [comment]
I found and fixed a couple bugs recently that I think should fix the item loss. If it starts again please open a new issue.
