### ISSUE TITLE
Anvil input costs XP

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#37]
Nice Anvil function, but the player that trades with money will lose 1 XP level due to the Anvil Enchantment Cost.
![Screenshot_20190524_213224](https://user-images.githubusercontent.com/28690790/58352380-a8329b00-7e6b-11e9-9243-d988ec97d5e8.png)

This makes the trade deal come with a bad taste if the player finds out, it did cost him more that the money he thought it would.

Tested with TradePlus 3.42

**Comment by Trophonix** [comment]
Oh jeez. I am using someone's library for that and I generally tested it in
creative so I didn't notice xp loss. I will fix it asap!

> Nice Anvil function, but the player that trades with money will lose 1 XP
> level due to the Anvil Enchantment Cost.
> [image: Screenshot_20190524_213224]
> <https://user-images.githubusercontent.com/28690790/58352380-a8329b00-7e6b-11e9-9243-d988ec97d5e8.png>
>
> This makes the trade deal come with a bad taste if the player finds out,
> it did cost him more that the money he thought it would.
>
> Tested with TradePlus 3.42
>

**Comment by Trophonix** [comment]
What version is your server?

**Comment by x1p** [comment]
Paper 1.13.2

**Comment by Trophonix** [comment]
I'm waiting for a response from the developer of the anvil gui library. In the meantime I'll be trying to write my own to get a fix out quickly.

**Comment by Trophonix** [comment]
I have something in the works to fix this but my power is out now due to a bad storm. I think I'm going to make an update changing it to chat input for now as soon as I have power again. Typing on my phone. Then when I can get the anvil gui fixed I will add it back as another option alongside increments and chat

**Comment by x1p** [comment]
sounds good
Good luck with the power.

**Comment by Trophonix** [comment]
See this update https://github.com/Trophonix/TradePlus/releases/tag/3.45

**Comment by x1p** [comment]
Typing works
