### ISSUE TITLE
Broken GUI, Cannot Put/Recieve Items.

### ISSUE THREAD

**Issue by KaloHG** [Trophonix/TradePlus#38]
I've been attempting to get this plugin working for the last 4ish hours, and have had no avail to it. You can send and accept a trade request. The issue occurs when the GUI opens, for some reason, the players cannot see or accept any items you put into the GUI. So per say, I want to trade some stone with someone. When I put the stone into the GUI, the other user cannot see it. They cannot accept the items either, as it is treated as an actual item instead of a button.

**Comment by Trophonix** [comment]
Oh no! Please in the future know that you can message me anytime for help,
no need to get frustrated trying to get it to work for hours! I will boot
up a test server and get a fix out by tonight. What server version are you
running?

> I've been attempting to get this plugin working for the last 4ish hours,
> and have had no avail to it. You can send and accept a trade request. The
> issue occurs when the GUI opens, for some reason, the players cannot see or
> accept any items you put into the GUI. So per say, I want to trade some
> stone with someone. When I put the stone into the GUI, the other user
> cannot see it. They cannot accept the items either, as it is treated as an
> actual item instead of a button.
>

**Comment by Trophonix** [comment]
Please try again with the update I just posted, version 3.42. If that's what you were already using or if the issue remains, can you let me know what version your server is? It isn't happening in 1.14 for me.

**Comment by Trophonix** [comment]
See this update https://github.com/Trophonix/TradePlus/releases/tag/3.45
