### ISSUE TITLE
GUI menu items

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#40]
Release 3.48 enables the possibility to earn the menu items. I can't use them for input of value's.
![Screenshot_20190607_110743](https://user-images.githubusercontent.com/28690790/59093550-84b02b80-8914-11e9-87b9-1476bc376594.png)

Paper 1.13.2 build 629
TradePlus 3.48

**Comment by Trophonix** [comment]
Ahh, I found the issue.

**Comment by Trophonix** [comment]
Fixed in 3.49

**Comment by x1p** [comment]
Only 1 of the players is able to accept the trade. The other can't accept it. After changing the offer, it is able to accept it, but then the other player must accept it again and clicking on this accept refuses just as the first player. So in the end: only 1 of the players can accept it.
