### ISSUE TITLE
Main thread

### ISSUE THREAD

**Issue by x1p** [Trophonix/TradePlus#41]
I was experimenting with a plugin called TruAntiLag. It notifies if plugins are trying to load on the main thread. I don't know what is true about this but maybe you can take a look to see what can be improved. Maybe it's nothing special or just a small thing...

https://hastebin.com/mowaxosuso.sql
TradePlus 3.49
Paper 1.13.2 build 631

**Comment by Trophonix** [comment]
That's.. Odd. I can't load things on another thread, it would have the
potential to cause problems if things didn't load before the code was
accessed. That's the point of a main thread. It would be unlikely to cause
problems but still seems like kind of bad code to me. Idk what that plugin
dev was thinking people should do. Looking at their github, they don't load
anything async in any of their other plugins so I have no idea what they
meant

**Comment by x1p** [comment]
I don't know either. I'm not into programming.
That git.io address contains maybe some clues. https://github.com/aikar/TaskChain/wiki/Why-TaskChain

**Comment by Trophonix** [comment]
From looking at their code, it seems like it will disable any plugin that makes any call on the main thread and it has literally a list of authors who's plugins to disable automatically. I wouldn't put too much stock in it tbh. 

I guess I will mess around with the suggestions there and if it doesn't mess anything up I could probably make a couple things async. Will be in an update soon if it works

**Comment by Trophonix** [comment]
I released an update with some async loading, 3.50

**Comment by x1p** [comment]
I can't tell the difference. It still being flagged as main thread. Many plugins are being flagged this way. It might only have to do with the startup of the plugin. So I doubt if this has any impact on server performance. So I give up. ;-)
