### ISSUE TITLE
Could not pass event InventoryClickEvent to TradePlus v3.59

### ISSUE THREAD

**Issue by Weasel-Beans** [Trophonix/TradePlus#45]
https://pastebin.com/F87FgkKS

These errors appeared while two players were trading.

Timings: https://timings.aikar.co/?id=bc4479f4929d40eb9233efa2c081db2a

**Comment by MaximeMichaud** [comment]
UP
Happen when updating my FactionsUUID b170 to b208

**Comment by Trophonix** [comment]
Sorry, have you tested the most recent update? I think I fixed this.

**Comment by Weasel-Beans** [comment]
I haven't seen the issue for a while, it may have been fixed

**Comment by MaximeMichaud** [comment]
I don't know, unfortunately,  I'm no longer using this plugin.
