### ISSUE TITLE
Bug Duplicate with XP level

### ISSUE THREAD

**Issue by DoctaEnkoda** [Trophonix/TradePlus#48]
Hello when i change XP level with an other player, he had level but big duplication because : 

i am 5 lvl XP
he as 600 lvl XP

if i trade with him, he has 605 lvl xp

**Comment by bartyrealms** [comment]
We just discovered this too. How has this not been fixed yet? This plugin is basically sneaking dupe bugs into many servers.

**Comment by Trophonix** [comment]
I don't understand exactly what's going on. Both players end up with the
xp? What version of Minecraft and are you using a fork of spigot like
paper?

**Comment by DoctaEnkoda** [comment]
I am 1.15.2 with PaperMC. 
Actualy when we trade : 

Player1 has 5 Level XP
Player2 has 100 Level XP

5 Levels + 100Levels in minecraft (points xp) dont send 105 but 100 + a little points xp

But actualy
5 lvl + 100 lvl = 105 lvl

**Comment by Trophonix** [comment]
Oh. I see what you mean. You can change the behavior in the config to use
xp instead of levels. I will work on changing it to use raw xp behind the
scenes and display the amount of levels the player would receive.

**Comment by Trophonix** [comment]
I removed level trading for now because the way the code handles levels and xp is insane and I couldn't get cross version compatibility with it, but xp point trading seems to work perfectly.
