### ISSUE TITLE
You can trade negative money and bad xp message

### ISSUE THREAD

**Issue by maks244** [Trophonix/TradePlus#49]
When trading with money you can put a negative amount and when you choose to trade more xp than you have it says "Your balance is 0" when it should say "You have 0 xp lvls" or something like that.

**Comment by Trophonix** [comment]
I fixed the negative trading issue and added an %EXTRA% keyword so you can make your message say "You have 5 experience" by putting something like "&cYou have %BALANCE% %EXTRA%"
