### ISSUE TITLE
10-20 seconds of lag cause by trade

### ISSUE THREAD

**Issue by afoxxvi** [Trophonix/TradePlus#62]
This happens when two player begin to trade. And then server stopped responding for several seconds, sometimes can up to 30s.
I don't think it's tolerable, this lag totally destroyed my game experience.
I believe slow Internet caused this, because my monitor plugin warned that TradePlus is connecting Internet on server main thread. And here is console log.
https://pastebin.com/g0ET4BJn
Please fix it, thanks

**Comment by CW-UK** [comment]
Can also confirm this issue. Massive lag spikes that drop the server to 12 TPS, when it runs at 20 consistently.

![image](https://user-images.githubusercontent.com/6217127/90152862-30a69f80-dd80-11ea-8c2b-b367cc62f1e3.png)

**Comment by leviem1** [comment]
Seems to be correlated to #60

**Comment by LakeArcFox** [comment]
> Seems to be correlated to #60 (at least for @CW-UK) since this is happening during the log save task from what I can tell. Though, I notice it after a trade is completed.

However in version 3.79.1 this problem still exists.
And the thread dump is totally same as before, caused by the plugin's network in main thread.
@Trophonix Could please have a look at this? This's really a very severe problem.

**Comment by LakeArcFox** [comment]
I guess by changing
com.trophonix.tradeplus.util.InvUtils line 59
`
    inv.setItem(
        pl.getTradeConfig().getAcceptSlot(),
        ItemFactory.getPlayerSkull(player1, "&f" + player1.getName()));
    inv.setItem(
        pl.getTradeConfig().getTheirAcceptSlot(),
        ItemFactory.getPlayerSkull(player2, "&f" + player2.getName()));
`
to
`
    if (pl.getTradeConfig().isHeadEnabled()){
        inv.setItem(
            pl.getTradeConfig().getAcceptSlot(),
            ItemFactory.getPlayerSkull(player1, "&f" + player1.getName()));
        inv.setItem(
            pl.getTradeConfig().getTheirAcceptSlot(),
            ItemFactory.getPlayerSkull(player2, "&f" + player2.getName()));
    }
`
can solve it if I disable head in config.

**Comment by Nezz202** [comment]
Hey. Did this fix work for you? This is a real issue on my server. I'm on 3.79.5 and still getting issue frequently with the server hanging for up to 30 seconds. I'm hesitant to change this as I'm not very knowledable with code ect, and don't want to cause more issues than it fixes. Thanks 👍

**Comment by LakeArcFox** [comment]
@Nezz202 
The code I given above works and solved my problem, and it's proved that the huge lag was caused by loading head textures.

@Trophonix 
Please fix this problem, it can be completed easily with a little work on method com.trophonix.tradeplus.util.InvUtils.getSpectatorInventory(). Thanks!

**Comment by Spiritho15** [comment]
any recent updates regarding this issue?

**Comment by leviem1** [comment]
@Spiritho15 I wrote a quick and dirty patch for this but it got hung up in review and I never heard from the plugin author afterwards. I ended up closing the PR due to inactivity.

**Comment by afoxxvi** [comment]
@Spiritho15 @leviem1 Already fixed very long ago.

**Comment by leviem1** [comment]
> @Spiritho15 @leviem1 Already fixed very long ago.

Oh sweet, didn't know about that. Can you close the issue @afoxxvi?

**Comment by afoxxvi** [comment]
I didn’t have noticed it, sorry.
