### ISSUE TITLE
Add NBT/Custom Model Data support to the GUI

### ISSUE THREAD

**Issue by nickpdx** [Trophonix/TradePlus#65]
Minecraft 1.14 added the CustomModelData NBT tag, which lets you add custom items without removing other ones. Support for CustomModelData, or NBT in general for items in the GUI would be cool to see.

**Comment by Trophonix** [comment]
The new GUI yml supports all item stack features if you know the format to
write in the yml, including custom model data. Im planning to make a new
GUI in game to make it easier to design your own trade menu :)
