### ISSUE TITLE
Suggestion - TokenEnchant Support

### ISSUE THREAD

**Issue by DeadMaster121** [Trophonix/TradePlus#7]
Add it so you can trade tokens (TokenEnchant Plugin) https://www.spigotmc.org/resources/tokenenchant.2287/

**Comment by Trophonix** [comment]
Will do!

**Comment by Trophonix** [comment]
Could you download the beta release I just published and let me know if everything works?

https://github.com/Trophonix/TradePlus/releases/tag/2.52-Beta

**Comment by DeadMaster121** [comment]
Tested it have found no issues so far, everything works smoothly, thank you!

**Comment by Trophonix** [comment]
Thanks! I'll merge to master and release soon.
